import datetime

eps_a_telemetry_ranges = {'BATC.CHRG_CURR': [0, 0.01],
                        'BATC.DCHRG_CURR': [0, 1.3],
                        'BATC.STATE': [3, 3], # ?
                        'BATC.TEMP': [15, 25],
                        'BATC.VOLT_A': [6.9, 8],
                        'BP.TEMP_A': [15, 25],
                        'BP.TEMP_B': [15, 25],
                        'CTRLA.PWR_CYCLES': [23345, 23445], # ~ 23345 on 2018-02-08
                        'CTRLA.SAFETY_CTR': [0, 10],
                        'CTRLA.SUPP_TEMP': [15, 30],
                        'CTRLA.TEMP': [15, 30],
                        'CTRLA.UPTIME': [datetime.timedelta(seconds=1), datetime.timedelta(seconds=2000)],
                        'CTRLB.VOLT_3V3d': [3.15, 3.45],
                        'DCDC3V3.TEMP': [15, 30],
                        'DCDC5V.TEMP': [15, 30],
                        'DISTR.CURR_3V3': [0, 0.4],
                        'DISTR.CURR_5V': [0, 0.9],
                        'DISTR.CURR_VBAT': [0, 0.2],
                        'DISTR.LCL_FLAGB': [127, 127],
                        'DISTR.LCL_STATE': [0, 0],
                        'DISTR.VOLT_3V3': [3.20, 3.45],
                        'DISTR.VOLT_5V': [4.8, 5.2],
                        'DISTR.VOLT_VBAT': [6.9, 8],
                        'MPPT_X.SOL_CURR': [0, 0.6],
                        'MPPT_X.SOL_OUT_VOLT': [0, 8.0],
                        'MPPT_X.SOL_VOLT': [0, 5.5],
                        'MPPT_X.STATE': [5, 5],
                        'MPPT_X.TEMP': [15, 30],
                        'MPPT_Y_MINUS.SOL_CURR': [0, 0.6],
                        'MPPT_Y_MINUS.SOL_OUT_VOLT': [0, 8.0],
                        'MPPT_Y_MINUS.SOL_VOLT': [0, 14],
                        'MPPT_Y_MINUS.STATE': [5, 5],
                        'MPPT_Y_MINUS.TEMP': [15, 30],
                        'MPPT_Y_PLUS.SOL_CURR': [0, 0.6],
                        'MPPT_Y_PLUS.SOL_OUT_VOLT': [0, 8.0],
                        'MPPT_Y_PLUS.SOL_VOLT': [0, 14],
                        'MPPT_Y_PLUS.STATE': [5, 5],
                        'MPPT_Y_PLUS.TEMP': [15, 30]}

eps_b_telemetry_ranges = {'BP.TEMP_C' : [15, 25],
                            'BATC.VOLT_B' : [6.9, 8],
                            'CTRLB.SAFETY_CTR' : [0, 10],
                            'CTRLB.PWR_CYCLES' : [45646, 45746],
                            'CTRLB.UPTIME' : [datetime.timedelta(seconds=1), datetime.timedelta(seconds=2000)],
                            'CTRLB.TEMP' : [15, 25],
                            'CTRLB.SUPP_TEMP' : [15, 25],
                            'CTRLA.VOLT_3V3d' : [3.15, 3.45]}